[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "Hades2GameDef"
versionNumber = "1.0.0"
description = "For mod developers only! Community sourced luaCATS definitions for Hades 2 in the context of ReturnOfModding"
websiteUrl = "https://github.com/SGG-Modding/Hades2GameDef"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.22"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
