---@meta game-Scripts-HUDData
local game = {}

---@class game-Scripts-HUDData*AmmoUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*AmmoUI
game.AmmoUI = ...
---@alias game-Scripts-HUDData.AmmoUI ...

---@class game-Scripts-HUDData*AxeUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*AxeUI
game.AxeUI = ...
---@alias game-Scripts-HUDData.AxeUI ...

---@class game-Scripts-HUDData*ConsumableUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*ConsumableUI
game.ConsumableUI = ...
---@alias game-Scripts-HUDData.ConsumableUI ...

---@class game-Scripts-HUDData*DaggerUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*DaggerUI
game.DaggerUI = ...
---@alias game-Scripts-HUDData.DaggerUI ...

---@class game-Scripts-HUDData*MoneyUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*MoneyUI
game.MoneyUI = ...
---@alias game-Scripts-HUDData.MoneyUI ...

---@class game-Scripts-HUDData*StaffUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*StaffUI
game.StaffUI = ...
---@alias game-Scripts-HUDData.StaffUI ...

---@class game-Scripts-HUDData*TorchUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*TorchUI
game.TorchUI = ...
---@alias game-Scripts-HUDData.TorchUI ...

---@class game-Scripts-HUDData*TraitUI : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-HUDData*TraitUI
game.TraitUI = ...
---@alias game-Scripts-HUDData.TraitUI ...

return game
