---@meta game-Scripts-MetaUpgradeData
local game = {}

---@class game-Scripts-MetaUpgradeData*MetaUpgradeCardData : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeCardData
game.MetaUpgradeCardData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeCardData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeCostData : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeCostData
game.MetaUpgradeCostData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeCostData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeData : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeData
game.MetaUpgradeData = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeData ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeDefaultCardLayout : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeDefaultCardLayout
game.MetaUpgradeDefaultCardLayout = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeDefaultCardLayout ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeLockOrder : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeLockOrder
game.MetaUpgradeLockOrder = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeLockOrder ...

---@class game-Scripts-MetaUpgradeData*MetaUpgradeSwapGameStateRequirement : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*MetaUpgradeSwapGameStateRequirement
game.MetaUpgradeSwapGameStateRequirement = ...
---@alias game-Scripts-MetaUpgradeData.MetaUpgradeSwapGameStateRequirement ...

---@class game-Scripts-MetaUpgradeData*RerollCosts : game-Scripts-*BaseData : game-Scripts-*BaseData

---@type game-Scripts-MetaUpgradeData*RerollCosts
game.RerollCosts = ...
---@alias game-Scripts-MetaUpgradeData.RerollCosts ...

return game
